// PAGE_CHIPS — AI-suggestie chips per pagina
// Gebruikt door AiAssistant.tsx en EmptyState.tsx
export const PAGE_CHIPS: Record<string, string[]> = {
  '/': ['Wat moet ik vandaag regelen?', 'Risico-events deze week', 'Lage voorraad voor volgend event', 'Omzet deze maand'],
  '/events': ['Voeg een nieuw event toe', 'Welke events komen eraan?', 'Maak een prep-lijst', 'Tip voor grote groepen'],
  '/events/[id]/hub': ['Briefing voor team', 'Inkooplijst genereren', 'Winstgevendheid van dit event', 'Prep-lijst maken'],
  '/events/[id]': ['Briefing voor team', 'Inkooplijst genereren', 'Winstgevendheid van dit event', 'Prep-lijst maken'],
  '/agenda': ['Maak een prep-lijst', 'Open taken afvinken', 'Taak toevoegen voor event', 'Planning komende week'],
  '/recepten': ['Bedenk nieuw signatuur-recept', 'Schaal recept naar 80 gasten', 'Dry rub voor brisket', 'Vergeten klassiekers herontdekken'],
  '/gerechten': ['20 gerechten met buikspek', 'Gerecht verwijderen', 'Vegetarische hapjes bedenken', 'Menubalans analyseren'],
  '/menu-engineering': ['Welke gerechten hebben beste marge?', 'Menu-analyse uitleggen', 'Stars vs Dogs in mijn menu', 'Gerecht verbeteren voor marge'],
  '/offertes': ['Welke offertes lopen vast?', 'Verlopen binnenkort', 'Follow-up advies vandaag', 'Nieuwe offerte aanmaken'],
  '/facturen': ['Nieuwe factuur aanmaken', 'Welke facturen vervallen binnenkort?', 'Openstaand overzicht', 'Cashflow advies'],
  '/voorraad': ['Wat moet ik bestellen voor het volgende event?', 'Lage voorraad nu', 'Bestel-suggestie genereren', 'Nieuw voorraad item'],
  '/inkoop': ['Inkooplijst aanmaken voor event', 'Leverancier toevoegen', 'Vleesinkoop calculeren voor 80p', 'Beste leverancier kiezen'],
  '/service': ['Open prep-taken nu', 'Temperatuur registreren', 'Vink alle prep af', 'Voorraad bijwerken'],
  '/haccp': ['Temperatuur registreren', 'Welke events missen HACCP?', 'Kerntemperaturen uitleggen', 'Gevaarlijke zone uitleg'],
  '/uren': ['Uren registreren voor vandaag', 'Weekoverzicht medewerkers', 'Overuren berekenen', 'Wettelijke limieten NL'],
  '/materieel': ['Welk materieel heeft onderhoud nodig?', 'Onderhoud registreren', 'Materieel toevoegen', 'Levensduur BBQ uitleggen'],
  '/logistiek': ['Wat is nog niet afgevinkt?', 'Bus inlaadvolgorde tips', 'Koelboxen checklist', 'Vergeten items check'],
  '/boekhouding': ['KPI overzicht', 'Verlopen facturen actie', 'BTW-aangifte tips', 'Food cost ratio berekenen'],
  '/financien': ['Beste maand analyse', 'Marge per maand vergelijken', 'Stille maanden aanpak', 'YoY groei berekenen'],
  '/price-intelligence': ['Leverancier vergelijken', 'Beste prijs-kwaliteit vlees', 'Inkoopprijs optimaliseren', 'Seizoensprijzen advies'],
  '/ai-chat': ['20 gerechten met buikspek', 'Thema-BBQ concepten', 'Zomermenu brainstorm', 'Onderscheidend vermogen tips'],
  '/klanten': ['Top 5 klanten op omzet', 'Wie heeft >6 maanden niets besteld?', 'Trouwste klanten op events', 'Klant herhaalboeking voorstel'],
  '/prep-counter': ['Hoeveel ben ik klaar?', 'Wat staat nog open?', 'Volgende prioriteit?', 'Klaar met deze taak'],
  '/klantgesprek': ['Wat moet ik vragen bij een intake?', 'Gemiddelde prijs per persoon', 'Hoeveel vlees per persoon?', 'Checklist klantbezoek'],
  '/foto-archief': ['Hoe organiseer ik foto\'s per event?', 'Categorisatie tips', 'Export naar klant', 'Watermark toevoegen'],
  '/mailbox': ['Mail naar klant sturen', 'E-mail template maken', 'Verzonden mails bekijken', 'Follow-up mail sturen'],
  '/gebruikers': ['Welke rollen zijn er?', 'Toegangsrechten instellen', 'Teamlid uitnodigen', 'Rolverdeling bij events'],
  '/website': ['Hoe update ik het menu?', 'SEO tips voor mijn website', 'Galerij beheren', 'FAQ toevoegen'],
  '/contact': ['Hoe bereik ik support?', 'Feedback geven', 'Feature aanvragen', 'Bug melden'],
  '/faq': ['Hoe maak ik een offerte?', 'HACCP uitleggen', 'Boekhouding koppelen', 'Veelgestelde vragen bekijken'],
};

// EmptyState configuratie per pagina
export const EMPTY_STATE_CONFIG: Record<string, { icon: string; title: string; description: string; actionLabel: string }> = {
  '/events': {
    icon: 'CalendarPlus',
    title: 'Nog geen events',
    description: 'Plan je eerste BBQ event en begin met het beheren van je catering-opdrachten.',
    actionLabel: 'Nieuw event plannen',
  },
  '/offertes': {
    icon: 'FileText',
    title: 'Nog geen offertes',
    description: 'Maak je eerste offerte aan voor een klant. Selecteer gerechten, stel prijzen in en verstuur.',
    actionLabel: 'Eerste offerte maken',
  },
  '/facturen': {
    icon: 'Receipt',
    title: 'Nog geen facturen',
    description: 'Facturen worden automatisch aangemaakt wanneer je een offerte accepteert. Of maak er handmatig een aan.',
    actionLabel: 'Factuur aanmaken',
  },
  '/voorraad': {
    icon: 'Package',
    title: 'Voorraad is leeg',
    description: 'Voeg je eerste ingrediënten toe of laat de AI ze genereren uit je recepten.',
    actionLabel: 'Ingrediënt toevoegen',
  },
  '/recepten': {
    icon: 'BookOpen',
    title: 'Nog geen recepten',
    description: 'Voeg je eerste BBQ-recept toe met ingrediënten, bereidingswijze en kostprijsberekening.',
    actionLabel: 'Recept toevoegen',
  },
  '/gerechten': {
    icon: 'UtensilsCrossed',
    title: 'Nog geen gerechten',
    description: 'Maak gerechten aan die je kunt aanbieden op je menu. Koppel ze aan recepten voor kostprijsberekening.',
    actionLabel: 'Gerecht toevoegen',
  },
  '/haccp': {
    icon: 'Thermometer',
    title: 'Geen HACCP-registraties',
    description: 'Log temperaturen voor voedselveiligheid. Verplicht voor elke professionele cateringoperatie.',
    actionLabel: 'Temperatuur registreren',
  },
  '/klanten': {
    icon: 'Users',
    title: 'Nog geen klanten',
    description: 'Voeg je eerste klant toe. Klantgegevens worden hergebruikt bij offertes en events.',
    actionLabel: 'Klant toevoegen',
  },
  '/inkoop': {
    icon: 'Truck',
    title: 'Nog geen inkoop-items',
    description: 'Beheer je leveranciers en inkooplijsten. Koppel ingrediënten aan leveranciers voor snelle bestellingen.',
    actionLabel: 'Leverancier toevoegen',
  },
  '/materieel': {
    icon: 'Wrench',
    title: 'Nog geen materieel',
    description: 'Registreer je BBQ\'s, koelboxen, tafels en ander materieel. Houd onderhoud en status bij.',
    actionLabel: 'Materieel toevoegen',
  },
  '/uren': {
    icon: 'Clock',
    title: 'Nog geen urenregistraties',
    description: 'Registreer werktijden voor je team. Punch in/out voor events en krijg automatisch weekoverzichten.',
    actionLabel: 'Start registratie',
  },
  '/agenda': {
    icon: 'Calendar',
    title: 'Geen items op deze dag',
    description: 'Plan events en taken via de agenda. Klik op een dag om details te zien of maak een nieuw event aan.',
    actionLabel: 'Nieuw event plannen',
  },
  '/logistiek': {
    icon: 'Truck',
    title: 'Nog geen logistiek items',
    description: 'Stel je bus-indeling, checklists en inpaklisten samen voor komende events.',
    actionLabel: 'Item toevoegen',
  },
  '/service': {
    icon: 'BellRing',
    title: 'Geen events met menu',
    description: 'Service mode werkt met events die een menu hebben. Maak eerst een event aan met gerechten.',
    actionLabel: 'Naar events',
  },
  '/menu-engineering': {
    icon: 'PieChart',
    title: 'Nog geen gerechten',
    description: 'Voeg gerechten toe om je menu te analyseren op marge, populariteit en winstgevendheid.',
    actionLabel: 'Gerecht toevoegen',
  },
  '/boekhouding': {
    icon: 'Calculator',
    title: 'Geen data beschikbaar',
    description: 'Boekhouding wordt automatisch gevuld met gegevens uit je facturen en offertes.',
    actionLabel: 'Naar facturen',
  },
  '/financien': {
    icon: 'Lock',
    title: 'Geen financiele data',
    description: 'Financiele analyse wordt opgebouwd uit geaccepteerde offertes, urenregistraties en foodcost-berekeningen.',
    actionLabel: 'Naar offertes',
  },
  '/foto-archief': {
    icon: 'Images',
    title: 'Geen foto\'s in archief',
    description: 'Upload foto\'s van events, gerechten en materieel voor documentatie en terugblik.',
    actionLabel: 'Upload foto',
  },
  '/price-intelligence': {
    icon: 'LineChart',
    title: 'Nog geen prijsdata',
    description: 'Importeer CSV-prijslijsten van leveranciers om prijzen te vergelijken en marges te beschermen.',
    actionLabel: 'Importeer prijzen',
  },
  '/gebruikers': {
    icon: 'UsersCog',
    title: 'Geen gebruikers',
    description: 'Voeg teamleden toe en wijs rollen toe voor je catering-operatie.',
    actionLabel: 'Gebruiker toevoegen',
  },
  '/mailbox': {
    icon: 'Inbox',
    title: 'Nog geen e-mails verzonden',
    description: 'Stuur je eerste e-mail naar een klant. Kies een template of schrijf een vrij bericht.',
    actionLabel: 'Nieuwe e-mail',
  },
};

// Allergenen — EU-14 lijst + veelvoorkomende dieetwensen
export const ALLERGENEN = [
  { code: 'gluten', label: 'Gluten', icon: '🌾' },
  { code: 'lactose', label: 'Lactose', icon: '🥛' },
  { code: 'ei', label: 'Ei', icon: '🥚' },
  { code: 'vis', label: 'Vis', icon: '🐟' },
  { code: 'schaaldieren', label: 'Schaaldieren', icon: '🦐' },
  { code: 'noten', label: 'Noten', icon: '🥜' },
  { code: 'pinda', label: 'Pinda', icon: '🥜' },
  { code: 'soja', label: 'Soja', icon: '🫘' },
  { code: 'selderij', label: 'Selderij', icon: '🌿' },
  { code: 'mosterd', label: 'Mosterd', icon: '🟡' },
  { code: 'sesam', label: 'Sesam', icon: '⚪' },
  { code: 'sulfiet', label: 'Sulfiet', icon: '🍷' },
];

export const DIEETWENSEN = [
  { code: 'vega', label: 'Vegetarisch', icon: '🌿' },
  { code: 'vegan', label: 'Veganistisch', icon: '🌱' },
  { code: 'halal', label: 'Halal', icon: '☪️' },
  { code: 'koosjier', label: 'Koosjier', icon: '✡️' },
];
