-- Price Intelligence: supplier invoice tables for AI-parsed invoices
-- Complements existing `bonnen` (receipts) and `supplier_prices` (CSV import)

CREATE TABLE IF NOT EXISTS supplier_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  leverancier TEXT DEFAULT 'Onbekend',
  factuurnummer TEXT,
  datum DATE,
  totaal_excl DECIMAL(10,2) DEFAULT 0,
  totaal_btw DECIMAL(10,2) DEFAULT 0,
  totaal_incl DECIMAL(10,2) DEFAULT 0,
  valuta TEXT DEFAULT 'EUR',
  file_url TEXT,
  status TEXT DEFAULT 'review' CHECK (status IN ('review', 'booked', 'archived')),
  notities TEXT,
  raw_ai_response JSONB
);

CREATE INDEX IF NOT EXISTS idx_supplier_invoices_org ON supplier_invoices(organization_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invoices_datum ON supplier_invoices(datum DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_invoices_leverancier ON supplier_invoices(leverancier);

ALTER TABLE supplier_invoices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "org_members_select_supplier_invoices" ON supplier_invoices
  FOR SELECT USING (organization_id IN (SELECT auth.user_org_ids()));
CREATE POLICY "org_members_insert_supplier_invoices" ON supplier_invoices
  FOR INSERT WITH CHECK (organization_id IN (SELECT auth.user_org_ids()));
CREATE POLICY "org_members_update_supplier_invoices" ON supplier_invoices
  FOR UPDATE USING (organization_id IN (SELECT auth.user_org_ids()));
CREATE POLICY "org_members_delete_supplier_invoices" ON supplier_invoices
  FOR DELETE USING (organization_id IN (SELECT auth.user_org_ids()));

CREATE TABLE IF NOT EXISTS supplier_invoice_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT REFERENCES supplier_invoices(id) ON DELETE CASCADE,
  product_naam TEXT NOT NULL,
  hoeveelheid DECIMAL(10,3) DEFAULT 1,
  eenheid TEXT DEFAULT 'stuks',
  prijs_per_eenheid DECIMAL(10,4) DEFAULT 0,
  btw_pct DECIMAL(5,2) DEFAULT 21,
  subtotaal DECIMAL(10,2) DEFAULT 0,
  categorie TEXT,
  notitie TEXT
);

CREATE INDEX IF NOT EXISTS idx_supplier_invoice_lines_invoice ON supplier_invoice_lines(invoice_id);

ALTER TABLE supplier_invoice_lines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "org_members_select_invoice_lines" ON supplier_invoice_lines
  FOR SELECT USING (invoice_id IN (SELECT id FROM supplier_invoices WHERE organization_id IN (SELECT auth.user_org_ids())));
CREATE POLICY "org_members_insert_invoice_lines" ON supplier_invoice_lines
  FOR INSERT WITH CHECK (invoice_id IN (SELECT id FROM supplier_invoices WHERE organization_id IN (SELECT auth.user_org_ids())));
CREATE POLICY "org_members_update_invoice_lines" ON supplier_invoice_lines
  FOR UPDATE USING (invoice_id IN (SELECT id FROM supplier_invoices WHERE organization_id IN (SELECT auth.user_org_ids())));
CREATE POLICY "org_members_delete_invoice_lines" ON supplier_invoice_lines
  FOR DELETE USING (invoice_id IN (SELECT id FROM supplier_invoices WHERE organization_id IN (SELECT auth.user_org_ids())));

-- Extend existing bonnen table for AI-parsed receipts
ALTER TABLE bonnen ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'review';
ALTER TABLE bonnen ADD COLUMN IF NOT EXISTS categorie TEXT;
ALTER TABLE bonnen ADD COLUMN IF NOT EXISTS btw_pct DECIMAL(5,2) DEFAULT 21;
