-- ============================================================
-- Inspiratie Bibliotheek — PR2 Schema
-- Date: 2026-05-10
--
-- Brengt de echte component-laag:
--   1. components            — atomair (prepared zelf-maken OF bought_in inkoop)
--   2. component_allergens   — allergeen-flags per component (hard-rule 2 compliant)
--   3. component_haccp_points — kritieke punten per component (kerntemp, etc.)
--   4. gerecht_components    — join: welk gerecht gebruikt welke component, hoeveel
--   5. supplier_products     — gedeeld met /inkoop (plan A)
--   6. gerechten.total_cost_cents — auto-rollup van gerecht_components.cost_at_use_cents
--   7. Triggers voor auto-cost-propagatie
--
-- Pillars: Components first-class + auto-propagatie + AI suggereert / mens bevestigt.
-- Hard-rule 2 (allergens): AI suggest, mens confirm, ground-truth in join-tables.
-- Hard-rule 5 (RLS): alle tabellen org-scoped via auth.user_org_ids() helper.
--
-- Safe to re-run (uses IF NOT EXISTS / DROP TRIGGER IF EXISTS).
-- ============================================================

-- Note: RLS-policies in deze migration gebruiken een inline subquery op
-- organization_members ipv de helper-functie auth.user_org_ids(). Reden:
-- Supabase verbiedt write-access op het auth schema vanuit SQL Editor,
-- en als migration 001 niet (volledig) gedraaid is, kunnen we de helper
-- niet aanvullen. Inline is robuuster en heeft dezelfde performance dankzij
-- de index op organization_members(user_id) + STABLE plan-caching.

-- ─── 1. components ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS components (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

    -- Identificatie
    name            TEXT NOT NULL,
    description     TEXT,

    -- Type: zelf-bereid (prepared) of inkoop (bought_in)
    type            TEXT NOT NULL CHECK (type IN ('prepared', 'bought_in')),

    -- Referentie-hoeveelheid + kost (basis voor terugrekenen in gerecht_components)
    -- Voorbeeld: 100g gegrilde ananas salsa kost €1,43 → base_quantity=100, base_unit='g', base_cost_cents=143
    base_quantity   NUMERIC(10,3) NOT NULL CHECK (base_quantity > 0),
    base_unit       TEXT NOT NULL,
    base_cost_cents INTEGER NOT NULL CHECK (base_cost_cents >= 0),

    -- Voor type=prepared
    ingredients         JSONB,          -- [{ name, qty, unit, cost_cents }]
    preparation_steps   JSONB,          -- ["snij ananas in blokjes", "grill 3 min", ...]
    flavor_tags         TEXT[],         -- ['zoet', 'zuur', 'pikant', 'rokerig'] voor AI-matching

    -- Voor type=bought_in (FK ingevuld als type='bought_in')
    supplier_product_id BIGINT,         -- FK naar supplier_products (toegevoegd na supplier_products create)

    -- AI-tracking (hard-rule 2 + provenance)
    ai_suggested    BOOLEAN DEFAULT false NOT NULL,
    approved_at     TIMESTAMPTZ,
    approved_by     UUID REFERENCES auth.users(id) ON DELETE SET NULL,

    created_at      TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at      TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_components_org_type ON components(organization_id, type);
CREATE INDEX IF NOT EXISTS idx_components_org_name ON components(organization_id, name);

COMMENT ON TABLE components IS
    'Inspiratie Bibliotheek (v5): atomaire bouwblokken. Type=prepared = zelf-maken (gegrilde ananas), '
    'type=bought_in = inkoop-product (Hanos broodje). Herbruikbaar in meerdere gerechten via gerecht_components.';

COMMENT ON COLUMN components.base_cost_cents IS
    'Kostprijs voor base_quantity (in cents om floating-point te vermijden). '
    'gerecht_components rekent terug: cost_at_use_cents = (quantity_used / base_quantity) * base_cost_cents';

-- ─── 2. supplier_products (gedeeld met /inkoop, plan A) ─────

CREATE TABLE IF NOT EXISTS supplier_products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    supplier_id     INTEGER REFERENCES leveranciers(id) ON DELETE SET NULL,
    supplier_sku    TEXT,

    name            TEXT NOT NULL,
    description     TEXT,
    price_cents     INTEGER NOT NULL CHECK (price_cents >= 0),
    unit            TEXT NOT NULL,                  -- 'stuk', 'kg', 'liter'
    package_size    NUMERIC(10,3),
    package_unit    TEXT,

    -- Optionele verrijking (v2 OrderXL, v3 GS1, v4 API)
    gtin            TEXT,                           -- barcode
    allergens       JSONB,
    nutrition       JSONB,

    source          TEXT NOT NULL DEFAULT 'manual_upload'
                        CHECK (source IN ('manual_upload', 'order_xl', 'gs1', 'api', 'invoice_ocr')),

    last_updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_supplier_products_org_supplier ON supplier_products(organization_id, supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_products_org_name ON supplier_products(organization_id, name);
CREATE INDEX IF NOT EXISTS idx_supplier_products_gtin ON supplier_products(gtin) WHERE gtin IS NOT NULL;

COMMENT ON TABLE supplier_products IS
    'Per-tenant leverancier-catalogus. Gevuld via /inkoop (factuur-OCR), handmatige upload (v1), '
    'OrderXL nightly drop (v2 roadmap), of GS1 Data Source (v3 roadmap). Gelezen door /inkoop EN /inspiratie/componenten.';

-- ─── Nu de FK van components.supplier_product_id koppelen ───

DO $fk$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_components_supplier_product'
          AND table_schema = 'public'
    ) THEN
        ALTER TABLE components
            ADD CONSTRAINT fk_components_supplier_product
            FOREIGN KEY (supplier_product_id) REFERENCES supplier_products(id) ON DELETE SET NULL;
    END IF;
END
$fk$;

CREATE INDEX IF NOT EXISTS idx_components_supplier ON components(supplier_product_id) WHERE supplier_product_id IS NOT NULL;

-- ─── 3. component_allergens (hard-rule 2 compliant join-table) ─

CREATE TABLE IF NOT EXISTS component_allergens (
    component_id    BIGINT NOT NULL REFERENCES components(id) ON DELETE CASCADE,
    allergen_code   TEXT NOT NULL,            -- EU14: 'G' gluten, 'L' lactose, 'N' noten, 'V' vis, 'E' ei, 'S' soja, ...
    ai_suggested    BOOLEAN DEFAULT false NOT NULL,
    confirmed_at    TIMESTAMPTZ,
    confirmed_by    UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

    PRIMARY KEY (component_id, allergen_code)
);

CREATE INDEX IF NOT EXISTS idx_component_allergens_org ON component_allergens(organization_id);
CREATE INDEX IF NOT EXISTS idx_component_allergens_component ON component_allergens(component_id);

COMMENT ON TABLE component_allergens IS
    'Allergenen per component. AI mag voorstellen (ai_suggested=true), mens bevestigt (confirmed_at set). '
    'Hard-rule 2: allergens NOOIT als AI-text in een veld; ALTIJD via deze join als ground-truth.';

-- ─── 4. component_haccp_points (kritieke punten per component) ─

CREATE TABLE IF NOT EXISTS component_haccp_points (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_id    BIGINT NOT NULL REFERENCES components(id) ON DELETE CASCADE,
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

    type            TEXT NOT NULL
                        CHECK (type IN ('kerntemp', 'koeltemp', 'tijd_uit_koeling',
                                        'handhygiene', 'kruisbesmetting', 'oppervlakte_reiniging', 'overig')),
    threshold_value NUMERIC,                    -- bv. 78 voor kerntemp
    threshold_unit  TEXT,                       -- 'celsius', 'minutes'
    note            TEXT,                       -- 'kerntemperatuur na 60s rust' / extra context

    ai_suggested    BOOLEAN DEFAULT false NOT NULL,
    confirmed_at    TIMESTAMPTZ,
    confirmed_by    UUID REFERENCES auth.users(id) ON DELETE SET NULL,

    created_at      TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_component_haccp_org ON component_haccp_points(organization_id);
CREATE INDEX IF NOT EXISTS idx_component_haccp_component ON component_haccp_points(component_id);

COMMENT ON TABLE component_haccp_points IS
    'HACCP-spec per component (kerntemp kip 78°C, koelketen vis <4°C, etc.). '
    'AI mag voorstellen, mens bevestigt. INSTANCES van metingen tijdens event leven in haccp_records (apart).';

-- ─── 5. gerecht_components (de join die alles bindt) ──────────

CREATE TABLE IF NOT EXISTS gerecht_components (
    gerecht_id          UUID NOT NULL REFERENCES gerechten(id) ON DELETE CASCADE,
    component_id        BIGINT NOT NULL REFERENCES components(id) ON DELETE RESTRICT,
    quantity_used       NUMERIC(10,3) NOT NULL CHECK (quantity_used > 0),
    unit                TEXT NOT NULL,
    -- Gedenormaliseerde kost (recomputed via trigger bij wijziging van component of quantity)
    cost_at_use_cents   INTEGER NOT NULL DEFAULT 0 CHECK (cost_at_use_cents >= 0),
    organization_id     UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    created_at          TIMESTAMPTZ DEFAULT now() NOT NULL,

    PRIMARY KEY (gerecht_id, component_id)
);

CREATE INDEX IF NOT EXISTS idx_gerecht_components_gerecht ON gerecht_components(gerecht_id);
CREATE INDEX IF NOT EXISTS idx_gerecht_components_component ON gerecht_components(component_id);
CREATE INDEX IF NOT EXISTS idx_gerecht_components_org ON gerecht_components(organization_id);

COMMENT ON TABLE gerecht_components IS
    'Welk gerecht gebruikt welke component, hoeveel. cost_at_use_cents = (quantity_used / component.base_quantity) * component.base_cost_cents, '
    'cached + auto-recomputed via trigger bij wijziging van component of quantity_used.';

-- ─── 6. gerechten.total_cost_cents (auto-rollup) ──────────────

ALTER TABLE gerechten
    ADD COLUMN IF NOT EXISTS total_cost_cents INTEGER NOT NULL DEFAULT 0;

COMMENT ON COLUMN gerechten.total_cost_cents IS
    'Auto-recomputed via trigger: SUM(gerecht_components.cost_at_use_cents) WHERE gerecht_id = gerechten.id. '
    'Bron-of-truth voor marge-berekening per gerecht. Geen handmatige updates.';

-- ─── 7. Trigger-functies ──────────────────────────────────────

-- 7a. Bij wijziging van een component (base_quantity of base_cost_cents)
--     → recompute alle gerecht_components.cost_at_use_cents waar dit component in zit
--     → recompute alle gerechten.total_cost_cents van die gerechten
CREATE OR REPLACE FUNCTION recompute_on_component_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    -- Update kost per gerecht_component-rij
    UPDATE gerecht_components gc
    SET cost_at_use_cents = GREATEST(0, ROUND((gc.quantity_used / NEW.base_quantity) * NEW.base_cost_cents)::INTEGER)
    WHERE gc.component_id = NEW.id;

    -- Update total_cost per gerecht dat dit component gebruikt
    UPDATE gerechten g
    SET total_cost_cents = COALESCE((
        SELECT SUM(cost_at_use_cents)
        FROM gerecht_components gc2
        WHERE gc2.gerecht_id = g.id
    ), 0)
    WHERE g.id IN (
        SELECT gerecht_id FROM gerecht_components WHERE component_id = NEW.id
    );

    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_component_cost_propagate ON components;
CREATE TRIGGER trg_component_cost_propagate
    AFTER UPDATE OF base_quantity, base_cost_cents
    ON components
    FOR EACH ROW
    WHEN (OLD.base_quantity IS DISTINCT FROM NEW.base_quantity
       OR OLD.base_cost_cents IS DISTINCT FROM NEW.base_cost_cents)
    EXECUTE FUNCTION recompute_on_component_change();

-- 7b. Bij INSERT/UPDATE/DELETE op gerecht_components
--     → recompute eigen cost_at_use_cents (bij INSERT/UPDATE)
--     → recompute gerechten.total_cost_cents van het betroffen gerecht
CREATE OR REPLACE FUNCTION recompute_on_gerecht_components_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    affected_gerecht_id UUID;
    component_base_qty  NUMERIC;
    component_base_cost INTEGER;
BEGIN
    -- Bepaal welk gerecht we updaten
    affected_gerecht_id := COALESCE(NEW.gerecht_id, OLD.gerecht_id);

    -- Bij INSERT/UPDATE: recompute cost_at_use_cents voor deze rij
    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        SELECT base_quantity, base_cost_cents
        INTO component_base_qty, component_base_cost
        FROM components
        WHERE id = NEW.component_id;

        IF component_base_qty IS NULL OR component_base_qty = 0 THEN
            NEW.cost_at_use_cents := 0;
        ELSE
            NEW.cost_at_use_cents := GREATEST(0, ROUND((NEW.quantity_used / component_base_qty) * component_base_cost)::INTEGER);
        END IF;
    END IF;

    -- Voor BEFORE-trigger op INSERT/UPDATE: return NEW zodat berekening gepersist wordt
    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        RETURN NEW;
    END IF;

    -- Voor DELETE: trigger AFTER zal total_cost_cents recompute doen
    RETURN OLD;
END;
$$;

-- BEFORE-trigger: berekent cost_at_use_cents voordat de rij gepersist wordt
DROP TRIGGER IF EXISTS trg_gc_compute_cost_before ON gerecht_components;
CREATE TRIGGER trg_gc_compute_cost_before
    BEFORE INSERT OR UPDATE OF quantity_used, component_id
    ON gerecht_components
    FOR EACH ROW
    EXECUTE FUNCTION recompute_on_gerecht_components_change();

-- AFTER-trigger: recomputed totalCost op gerechten na elke INSERT/UPDATE/DELETE
CREATE OR REPLACE FUNCTION recompute_gerecht_total_after()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    affected_gerecht_id UUID;
BEGIN
    affected_gerecht_id := COALESCE(NEW.gerecht_id, OLD.gerecht_id);

    UPDATE gerechten
    SET total_cost_cents = COALESCE((
        SELECT SUM(cost_at_use_cents)
        FROM gerecht_components
        WHERE gerecht_id = affected_gerecht_id
    ), 0)
    WHERE id = affected_gerecht_id;

    RETURN NULL;  -- AFTER-trigger: return value wordt genegeerd
END;
$$;

DROP TRIGGER IF EXISTS trg_gc_recompute_total_after ON gerecht_components;
CREATE TRIGGER trg_gc_recompute_total_after
    AFTER INSERT OR UPDATE OR DELETE
    ON gerecht_components
    FOR EACH ROW
    EXECUTE FUNCTION recompute_gerecht_total_after();

-- ─── 8. RLS — alle nieuwe tabellen ───────────────────────────

ALTER TABLE components            ENABLE ROW LEVEL SECURITY;
ALTER TABLE supplier_products     ENABLE ROW LEVEL SECURITY;
ALTER TABLE component_allergens   ENABLE ROW LEVEL SECURITY;
ALTER TABLE component_haccp_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE gerecht_components    ENABLE ROW LEVEL SECURITY;

-- Standaard org-scoped policies — INLINE subquery (geen helper-functie)
-- voor robuustheid tegen ontbrekend/locked auth-schema.
DO $rls$
DECLARE
    tbl TEXT;
    org_check TEXT := 'organization_id IN (SELECT om.organization_id FROM public.organization_members om WHERE om.user_id = auth.uid() AND om.status = ''active'')';
BEGIN
    FOR tbl IN
        SELECT unnest(ARRAY[
            'components',
            'supplier_products',
            'component_allergens',
            'component_haccp_points',
            'gerecht_components'
        ])
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "org_select" ON %I', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "org_insert" ON %I', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "org_update" ON %I', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "org_delete" ON %I', tbl);

        EXECUTE format('CREATE POLICY "org_select" ON %I FOR SELECT USING (%s)', tbl, org_check);
        EXECUTE format('CREATE POLICY "org_insert" ON %I FOR INSERT WITH CHECK (%s)', tbl, org_check);
        EXECUTE format('CREATE POLICY "org_update" ON %I FOR UPDATE USING (%s)', tbl, org_check);
        EXECUTE format('CREATE POLICY "org_delete" ON %I FOR DELETE USING (%s)', tbl, org_check);
    END LOOP;
END
$rls$;

-- ============================================================
-- End PR2 schema migration
-- ============================================================
