-- ============================================================
-- Unify Gerechten + Componenten + Ingrediënten — PR slice 1
-- Date: 2026-05-16
--
-- Brengt:
--   1. allergens             — master EU14-tabel (read-public, geen RLS)
--   2. ingredient_allergens  — join inventory ↔ allergens (hard-rule 2 source-of-truth)
--   3. component_ingredients — join components ↔ inventory (vervangt JSONB op termijn)
--   4. gerecht_allergens_mv  — materialized view: cascade ingredient→component→gerecht
--   5. refresh-triggers + helper voor on-demand refresh
--
-- Pillar #1 (Provenance): source_chain JSONB toont herkomst per allergen-claim
-- Pillar #2 (Cascade): MV is EU 1169/2011 evidence-chain compliant
-- Pillar #3 (Margin): geen client-side calcs nodig — bestaande triggers staan al
-- Pillar #4 (Reuse): component-reuse count via SQL group-by op gerecht_components
--
-- BACKWARDS-COMPAT: gerechten.allergenen (text[]) blijft 1 release als read-cache,
-- nieuwe writes gaan naar component_allergens. Drop in slice 2.
--
-- Safe to re-run: IF NOT EXISTS guards + DROP TRIGGER IF EXISTS.
-- ============================================================

-- ─── 1. allergens master ────────────────────────────────────
-- EU 1169/2011 Annex II — 14 verplichte allergenen voor EU-foodservice.
-- Public read, geen RLS (statisch reference data).

CREATE TABLE IF NOT EXISTS allergens (
    code               TEXT PRIMARY KEY,
    nl_label           TEXT NOT NULL,
    eu_official_label  TEXT NOT NULL,
    ce_required        BOOLEAN NOT NULL DEFAULT true,
    sort_order         INTEGER NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMENT ON TABLE allergens IS
    'EU 1169/2011 Annex II — 14 verplichte allergenen voor foodservice. '
    'Reference data, geen RLS. Codes komen overeen met /api/detect-allergens output.';

-- Seed (idempotent via ON CONFLICT DO NOTHING).
INSERT INTO allergens (code, nl_label, eu_official_label, sort_order) VALUES
    ('G',  'Gluten',              'Cereals containing gluten',          1),
    ('L',  'Lactose/zuivel',      'Milk and products thereof',          2),
    ('N',  'Noten',               'Nuts',                                3),
    ('P',  'Pinda',               'Peanuts and products thereof',       4),
    ('E',  'Ei',                  'Eggs and products thereof',          5),
    ('S',  'Soja',                'Soybeans and products thereof',      6),
    ('F',  'Vis',                 'Fish and products thereof',          7),
    ('C',  'Schaaldieren',        'Crustaceans and products thereof',   8),
    ('W',  'Weekdieren',          'Molluscs and products thereof',      9),
    ('M',  'Mosterd',             'Mustard and products thereof',      10),
    ('SE', 'Sesam',               'Sesame seeds and products thereof', 11),
    ('SU', 'Sulfiet (>10mg/kg)',  'Sulphur dioxide and sulphites',     12),
    ('SD', 'Selderij',            'Celery and products thereof',       13),
    ('LU', 'Lupine',              'Lupin and products thereof',        14),
    -- Niet-EU14 maar in onze /api/detect-allergens code aanwezig:
    ('V',  'Vegetarisch',         'Vegetarian (proxy flag)',           90),
    ('VE', 'Vegan',               'Vegan (proxy flag)',                91)
ON CONFLICT (code) DO NOTHING;

-- ─── 2. ingredient_allergens — join inventory ↔ allergens ────
-- Hard-rule 2: AI suggereert (ai_suggested=true), mens bevestigt (confirmed_at).
-- Dit is de SOURCE OF TRUTH voor allergens-per-ingredient.

CREATE TABLE IF NOT EXISTS ingredient_allergens (
    inventory_id     INTEGER NOT NULL REFERENCES inventory(id) ON DELETE CASCADE,
    allergen_code    TEXT    NOT NULL REFERENCES allergens(code) ON DELETE RESTRICT,
    organization_id  UUID    NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

    ai_suggested     BOOLEAN NOT NULL DEFAULT false,
    confirmed_at     TIMESTAMPTZ,
    confirmed_by     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    notes            TEXT,

    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (inventory_id, allergen_code)
);

CREATE INDEX IF NOT EXISTS idx_ingredient_allergens_org ON ingredient_allergens(organization_id);
CREATE INDEX IF NOT EXISTS idx_ingredient_allergens_inventory ON ingredient_allergens(inventory_id);

COMMENT ON TABLE ingredient_allergens IS
    'Allergeen per ingredient (inventory-item). AI mag voorstellen (ai_suggested=true), '
    'mens bevestigt (confirmed_at set). Dit is de FUNDAMENT van de cascade ingredient→component→gerecht.';

-- ─── 3. component_ingredients — join components ↔ inventory ──
-- Normaliseert components.ingredients JSONB naar een echte FK.
-- Bestaande JSONB-data blijft 1 release, helper-function backfilled.

CREATE TABLE IF NOT EXISTS component_ingredients (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_id     BIGINT NOT NULL REFERENCES components(id) ON DELETE CASCADE,
    inventory_id     INTEGER REFERENCES inventory(id) ON DELETE RESTRICT,
    organization_id  UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

    -- Voor unmatched items (AI heeft een ingredient genoemd dat niet in inventory zit)
    -- mag inventory_id NULL zijn. Dan vult fallback_name de naam in.
    fallback_name    TEXT,
    quantity         NUMERIC(10,3) NOT NULL CHECK (quantity > 0),
    unit             TEXT NOT NULL,
    -- Yield-override per gebruik (default = inventory.yield_factor).
    -- Pillar #1 research: dubbele yield-loss aware foodcost (raw × prep).
    yield_override   NUMERIC(5,3),

    notes            TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_inventory_or_fallback CHECK (
        inventory_id IS NOT NULL OR fallback_name IS NOT NULL
    )
);

CREATE INDEX IF NOT EXISTS idx_component_ingredients_component ON component_ingredients(component_id);
CREATE INDEX IF NOT EXISTS idx_component_ingredients_inventory ON component_ingredients(inventory_id) WHERE inventory_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_component_ingredients_org ON component_ingredients(organization_id);

COMMENT ON TABLE component_ingredients IS
    'Genormaliseerde ingredient-link van components naar inventory. '
    'Vervangt components.ingredients JSONB. Bij geen inventory-match: fallback_name. '
    'yield_override laat per-gebruik prep-yield variatie toe (apart van inventory.yield_factor).';

-- ─── 4. RLS op nieuwe joins ─────────────────────────────────

ALTER TABLE ingredient_allergens   ENABLE ROW LEVEL SECURITY;
ALTER TABLE component_ingredients  ENABLE ROW LEVEL SECURITY;

DO $rls$
DECLARE
    tbl TEXT;
    org_check TEXT := 'organization_id IN (SELECT om.organization_id FROM public.organization_members om WHERE om.user_id = (SELECT auth.uid()) AND om.status = ''active'')';
BEGIN
    FOR tbl IN
        SELECT unnest(ARRAY['ingredient_allergens', 'component_ingredients'])
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "org_select" ON %I', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "org_insert" ON %I', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "org_update" ON %I', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "org_delete" ON %I', tbl);

        EXECUTE format('CREATE POLICY "org_select" ON %I FOR SELECT USING (%s)', tbl, org_check);
        EXECUTE format('CREATE POLICY "org_insert" ON %I FOR INSERT WITH CHECK (%s)', tbl, org_check);
        EXECUTE format('CREATE POLICY "org_update" ON %I FOR UPDATE USING (%s)', tbl, org_check);
        EXECUTE format('CREATE POLICY "org_delete" ON %I FOR DELETE USING (%s)', tbl, org_check);
    END LOOP;
END
$rls$;

-- Allergens master = public read (geen WRITE policy, alleen migration mag inserten)
ALTER TABLE allergens ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public_read" ON allergens;
CREATE POLICY "public_read" ON allergens FOR SELECT USING (true);

-- ─── 5. Materialized view: gerecht_allergens_mv ──────────────
-- Cascade: ingredient → component → gerecht
-- source_chain bevat de bewijs-keten voor EU 1169/2011 audit.

CREATE MATERIALIZED VIEW IF NOT EXISTS gerecht_allergens_mv AS
SELECT
    gc.gerecht_id,
    gc.organization_id,
    ia.allergen_code,
    bool_or(ia.confirmed_at IS NOT NULL) AS any_confirmed,
    bool_or(ia.ai_suggested AND ia.confirmed_at IS NULL) AS has_unconfirmed_ai,
    jsonb_agg(DISTINCT jsonb_build_object(
        'inventory_id', ci.inventory_id,
        'fallback_name', ci.fallback_name,
        'component_id', gc.component_id,
        'confirmed', ia.confirmed_at IS NOT NULL,
        'ai_suggested', ia.ai_suggested
    )) AS source_chain
FROM gerecht_components gc
JOIN component_ingredients ci ON ci.component_id = gc.component_id
JOIN ingredient_allergens ia ON ia.inventory_id = ci.inventory_id
GROUP BY gc.gerecht_id, gc.organization_id, ia.allergen_code;

-- Note: materialized views in Postgres ondersteunen geen UNIQUE INDEX op een
-- view zonder REFRESH MATERIALIZED VIEW CONCURRENTLY. Daarom maken we hem
-- expliciet ondersteunend voor concurrent refresh.
CREATE UNIQUE INDEX IF NOT EXISTS idx_gerecht_allergens_mv_pk
    ON gerecht_allergens_mv (gerecht_id, allergen_code);

CREATE INDEX IF NOT EXISTS idx_gerecht_allergens_mv_org
    ON gerecht_allergens_mv (organization_id);

COMMENT ON MATERIALIZED VIEW gerecht_allergens_mv IS
    'Pillar #2: cascade ingredient→component→gerecht voor allergenen. '
    'source_chain levert EU 1169/2011 audit-evidence. Refresh via refresh_gerecht_allergens_mv().';

-- ─── 6. Helper: refresh on demand ────────────────────────────

CREATE OR REPLACE FUNCTION refresh_gerecht_allergens_mv()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    -- CONCURRENTLY = niet-blocking voor readers. Vereist unique index (zie boven).
    REFRESH MATERIALIZED VIEW CONCURRENTLY gerecht_allergens_mv;
EXCEPTION
    WHEN OTHERS THEN
        -- Fall back op non-concurrent refresh als concurrent faalt (bv. eerste refresh)
        REFRESH MATERIALIZED VIEW gerecht_allergens_mv;
END;
$$;

COMMENT ON FUNCTION refresh_gerecht_allergens_mv() IS
    'On-demand refresh van gerecht_allergens_mv. Roept Server Actions aan na '
    'mutaties op ingredient_allergens of component_ingredients. '
    'CONCURRENTLY zodat readers niet blokkeren.';

-- ─── 7. Trigger-glue: auto-refresh bij allergen/ingredient changes ──
-- Trigger het MV-refresh statement nadat een rij wijzigt. Voor lage write-volume
-- (component-curatie, allergen-bevestiging) is dit acceptabel. Bij hogere
-- write-volume kunnen we naar een job-queue verschuiven.

CREATE OR REPLACE FUNCTION trigger_refresh_gerecht_allergens()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    -- Asynchroon zou ideaal zijn maar pg_notify + worker is overkill voor v1.
    -- Refresh inline; concurrent zorgt dat readers niet blokkeren.
    PERFORM refresh_gerecht_allergens_mv();
    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_refresh_mv_on_ingredient_allergens ON ingredient_allergens;
CREATE TRIGGER trg_refresh_mv_on_ingredient_allergens
    AFTER INSERT OR UPDATE OR DELETE ON ingredient_allergens
    FOR EACH STATEMENT
    EXECUTE FUNCTION trigger_refresh_gerecht_allergens();

DROP TRIGGER IF EXISTS trg_refresh_mv_on_component_ingredients ON component_ingredients;
CREATE TRIGGER trg_refresh_mv_on_component_ingredients
    AFTER INSERT OR UPDATE OR DELETE ON component_ingredients
    FOR EACH STATEMENT
    EXECUTE FUNCTION trigger_refresh_gerecht_allergens();

DROP TRIGGER IF EXISTS trg_refresh_mv_on_gerecht_components ON gerecht_components;
CREATE TRIGGER trg_refresh_mv_on_gerecht_components
    AFTER INSERT OR UPDATE OR DELETE ON gerecht_components
    FOR EACH STATEMENT
    EXECUTE FUNCTION trigger_refresh_gerecht_allergens();

-- ─── 8. Helper: backfill ingredient_allergens uit inventory.allergenen ──
-- inventory.allergenen is een legacy text[] kolom. Migrate naar genormaliseerde join.
-- ai_suggested=false voor bestaande data (mens heeft ze ooit gezet) — maar
-- confirmed_at=NULL zodat de UI weet ze nog tonen voor revisit.

CREATE OR REPLACE FUNCTION backfill_ingredient_allergens()
RETURNS TABLE (inserted_count INTEGER, skipped_count INTEGER)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_inserted INTEGER := 0;
    v_skipped INTEGER := 0;
    v_rec RECORD;
    v_allergen TEXT;
    v_org_id UUID;
    v_normalized TEXT;
BEGIN
    FOR v_rec IN
        SELECT i.id AS inventory_id, i.allergenen, i.organization_id
        FROM inventory i
        WHERE i.allergenen IS NOT NULL
          AND array_length(i.allergenen, 1) > 0
          AND i.organization_id IS NOT NULL
    LOOP
        v_org_id := v_rec.organization_id;

        FOREACH v_allergen IN ARRAY v_rec.allergenen
        LOOP
            -- Normaliseer (lowercase, trim) en map naar allergen-code.
            v_normalized := LOWER(TRIM(v_allergen));
            -- Probeer eerst exact-match op nl_label, dan op code.
            DECLARE
                v_code TEXT;
            BEGIN
                SELECT code INTO v_code FROM allergens
                WHERE LOWER(nl_label) = v_normalized
                   OR LOWER(code) = v_normalized
                LIMIT 1;

                IF v_code IS NULL THEN
                    v_skipped := v_skipped + 1;
                    CONTINUE;
                END IF;

                INSERT INTO ingredient_allergens (
                    inventory_id, allergen_code, organization_id,
                    ai_suggested, confirmed_at
                ) VALUES (
                    v_rec.inventory_id, v_code, v_org_id,
                    false, NULL  -- bestaande data → niet AI, maar wel revisit-needed
                )
                ON CONFLICT (inventory_id, allergen_code) DO NOTHING;

                IF FOUND THEN
                    v_inserted := v_inserted + 1;
                END IF;
            END;
        END LOOP;
    END LOOP;

    RETURN QUERY SELECT v_inserted, v_skipped;
END;
$$;

COMMENT ON FUNCTION backfill_ingredient_allergens() IS
    'One-shot migration helper: kopieert inventory.allergenen[] naar ingredient_allergens. '
    'Run ÉÉN keer na deze migration met SELECT * FROM backfill_ingredient_allergens(); '
    'Idempotent (ON CONFLICT DO NOTHING).';

-- ─── 9. Initial refresh van de MV zodat hij niet leeg is ─────

DO $init$
BEGIN
    PERFORM refresh_gerecht_allergens_mv();
EXCEPTION
    WHEN OTHERS THEN
        -- Bij eerste run kunnen er geen rijen zijn, dat is OK
        NULL;
END
$init$;

-- ============================================================
-- End unify migration
-- ============================================================
