-- ════════════════════════════════════════════════════════════════════════
-- P0.12 — bon_share_tokens: deelbare read-only link voor boekhouder.
--
-- Use case: cateraar wil boekhouder toegang geven tot een gefilterd
-- subset van bonnen (bv. "Mei 2026, alle leveranciers") zonder account.
--
-- Werking:
--   - Cateraar maakt link via DeelLinkSheet (UI uit Claude design).
--   - Server genereert cryptografisch random token (32 random bytes hex = 64 chars).
--   - Boekhouder opent https://app.bbq-architect.nl/share/{token}.
--   - Public route resolves token → org_id + filter_json + expires_at.
--   - Read-only view: zoeken, preview, bulk-export. Geen edit, geen lock.
--   - Token vervalt automatisch (TTL 7/30/90 dagen, default 30).
--   - Access wordt gelogd in access_count + last_accessed_at.
--   - Intrekken via UI: zet revoked_at i.p.v. DELETE (audit-trail behoud).
-- ════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS bon_share_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token TEXT NOT NULL UNIQUE,
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

    -- Filter-snapshot: bevroren bij creatie zodat boekhouder geen bredere set
    -- ziet als cateraar later filters wijzigt. Shape matcht SearchInput uit DAL.
    filter_json JSONB NOT NULL DEFAULT '{}'::jsonb,

    -- Optionele context voor de boekhouder.
    recipient_name TEXT,
    recipient_email TEXT,
    label TEXT,                              -- bv. "Mei 2026 voor Jan de Boer"

    -- Lifecycle.
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,                  -- intrekken: zet timestamp, niet DELETE
    access_count INTEGER NOT NULL DEFAULT 0,
    last_accessed_at TIMESTAMPTZ,
    last_accessed_ip INET,                   -- audit trail (AVG: legitimate interest)

    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS bon_share_tokens_token_idx ON bon_share_tokens(token);
CREATE INDEX IF NOT EXISTS bon_share_tokens_org_idx   ON bon_share_tokens(organization_id);
CREATE INDEX IF NOT EXISTS bon_share_tokens_active_idx
    ON bon_share_tokens(organization_id, expires_at)
    WHERE revoked_at IS NULL;

COMMENT ON TABLE bon_share_tokens IS
    'Pillar #4 — deelbare read-only links voor boekhouder. Token = 64-char hex string (32 random bytes). Resolved server-side in /api/share/[token].';

COMMENT ON COLUMN bon_share_tokens.filter_json IS
    'Bevroren filter-snapshot. Cateraar kan filters later wijzigen zonder dat de share-link breder wordt.';

COMMENT ON COLUMN bon_share_tokens.revoked_at IS
    'Intrekken via UI: zet timestamp i.p.v. DELETE, zodat audit-trail behouden blijft.';

-- RLS — alleen eigen org ziet zijn share-tokens. Het publieke /share/[token]
-- endpoint gebruikt service_role om token op te zoeken (omzeilt RLS, want anon).
ALTER TABLE bon_share_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY share_tokens_select ON bon_share_tokens
    FOR SELECT TO authenticated
    USING (organization_id IN (SELECT auth.user_org_ids()));

CREATE POLICY share_tokens_insert ON bon_share_tokens
    FOR INSERT TO authenticated
    WITH CHECK (
        organization_id IN (SELECT auth.user_org_ids())
        AND created_by = auth.uid()
    );

-- Update: alleen revoken + label/recipient bijwerken.
-- Token + filter_json + expires_at + created_by zijn de facto immutable
-- (UI biedt ze niet aan om te wijzigen).
CREATE POLICY share_tokens_update ON bon_share_tokens
    FOR UPDATE TO authenticated
    USING (organization_id IN (SELECT auth.user_org_ids()))
    WITH CHECK (organization_id IN (SELECT auth.user_org_ids()));

-- DELETE alleen voor ongebruikte tokens (anders houd je revoked_at-trail).
CREATE POLICY share_tokens_delete ON bon_share_tokens
    FOR DELETE TO authenticated
    USING (
        organization_id IN (SELECT auth.user_org_ids())
        AND access_count = 0
    );
